name: My first WorkFlow

on:
  push:
    branches: ["main"]

jobs: #Creo que un job significa trabajar en una maquina
  saludar:
    runs-on: ubuntu-latest

    steps:
    - name: Mostrar "Hello World"
      run: echo "Hello World!!!"

  fecha:
    runs-on: ubuntu-latest

    steps:
    - name: Dime la fecha
      run: date

    - name: Muestra contenido de carpeta
      run: ls -la